# Generated by Django 5.2.15 on 2026-06-06 14:57

import django.db.models.deletion
import files.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255, verbose_name='Оригинальное имя')),
                ('file', models.FileField(upload_to=files.models.user_directory_path, verbose_name='Файл')),
                ('file_size', models.BigIntegerField(verbose_name='Размер (байты)')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('last_download_date', models.DateTimeField(blank=True, null=True, verbose_name='Последнее скачивание')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('special_link', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Спец. ссылка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
    ]
